CREATE TABLE IF NOT EXISTS PAGOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    METODO_PAGO VARCHAR(50) NOT NULL,
    DETALLE VARCHAR(50) NOT NULL,
    MONTO_PAGO DOUBLE NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    ACEPTADO BOOLEAN NOT NULL,
    PEDIDO_ID INT NOT NULL
);