server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/api/v1/usuarios/**,/api/v1/perfiles/**

            - id: ms-productos
              uri: lb://ms-productos
              predicates:
                - Path=/api/v1/productos/**,/api/v1/categorias/**

            - id: ms-inventario
              uri: lb://ms-inventario
              predicates:
                - Path=/api/v1/inventario/**,/api/v1/movimientos/**

            - id: ms-pedidos
              uri: lb://ms-pedidos
              predicates:
                - Path=/api/v1/pedidos/**,/api/v1/detalles-pedido/**

            - id: ms-pagos
              uri: lb://ms-pagos
              predicates:
                - Path=/api/v1/pagos/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true