CREATE TABLE IF NOT EXISTS INVENTARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SECCION VARCHAR(50) NOT NULL,
    CANTIDAD_DISPONIBLE INT NOT NULL,
    UBICACION VARCHAR(50) NOT NULL,
    ACTIVO BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL,
    PRODUCTO_ID INT NOT NULL
);
CREATE TABLE IF NOT EXISTS MOVIMIENTO_STOCK(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_MOVIMIENTO VARCHAR(30) NOT NULL,
    MOTIVO VARCHAR(100) NOT NULL,
    CANTIDAD INT NOT NULL,
    APROBADO BOOLEAN NOT NULL,
    FECHA_MOVIMIENTO DATE NOT NULL,
    INVENTARIO_ID INT NOT NULL,
    CONSTRAINT FK_MOVIMIENTO_INVENTARIO
    FOREIGN KEY(INVENTARIO_ID)
    REFERENCES INVENTARIO(ID)
);